/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module fpga_pwm8(clk, \duty[0] , \duty[1] , \duty[2] , \duty[3] , \duty[4] , \duty[5] , \duty[6] , \duty[7] , \period[0] , \period[1] , \period[2] , \period[3] , \period[4] , \period[5] , \period[6] , \period[7] , pwm);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  input clk;
  wire clk;
  reg \cntr[0]  = 1'h0;
  reg \cntr[1]  = 1'h0;
  reg \cntr[2]  = 1'h0;
  reg \cntr[3]  = 1'h0;
  reg \cntr[4]  = 1'h0;
  reg \cntr[5]  = 1'h0;
  reg \cntr[6]  = 1'h0;
  reg \cntr[7]  = 1'h0;
  input \duty[0] ;
  wire \duty[0] ;
  input \duty[1] ;
  wire \duty[1] ;
  input \duty[2] ;
  wire \duty[2] ;
  input \duty[3] ;
  wire \duty[3] ;
  input \duty[4] ;
  wire \duty[4] ;
  input \duty[5] ;
  wire \duty[5] ;
  input \duty[6] ;
  wire \duty[6] ;
  input \duty[7] ;
  wire \duty[7] ;
  wire n38;
  wire n42;
  wire n47;
  wire n52;
  wire n57;
  wire n62;
  wire n67;
  wire n72;
  wire n77;
  input \period[0] ;
  wire \period[0] ;
  input \period[1] ;
  wire \period[1] ;
  input \period[2] ;
  wire \period[2] ;
  input \period[3] ;
  wire \period[3] ;
  input \period[4] ;
  wire \period[4] ;
  input \period[5] ;
  wire \period[5] ;
  input \period[6] ;
  wire \period[6] ;
  input \period[7] ;
  wire \period[7] ;
  output pwm;
  reg pwm = 1'h0;
  always @(posedge clk)
    pwm <= n38;
  always @(posedge clk)
    \cntr[0]  <= n42;
  always @(posedge clk)
    \cntr[1]  <= n47;
  always @(posedge clk)
    \cntr[2]  <= n52;
  always @(posedge clk)
    \cntr[3]  <= n57;
  always @(posedge clk)
    \cntr[4]  <= n62;
  always @(posedge clk)
    \cntr[5]  <= n67;
  always @(posedge clk)
    \cntr[6]  <= n72;
  always @(posedge clk)
    \cntr[7]  <= n77;
  assign n42 = 8'hc5 >> { _00_, \period[0] , \cntr[0]  };
  assign _00_ = 4'h4 >> { _01_, \cntr[7]  };
  assign _01_ = 16'h0100 >> { _02_, \cntr[6] , \cntr[4] , \cntr[5]  };
  assign _02_ = 16'h0001 >> { \cntr[0] , \cntr[2] , \cntr[3] , \cntr[1]  };
  assign n47 = 16'haac3 >> { _00_, \cntr[0] , \cntr[1] , \period[1]  };
  assign n52 = 8'hc5 >> { _00_, \period[2] , _03_ };
  assign _03_ = 8'h1e >> { \cntr[2] , \cntr[0] , \cntr[1]  };
  assign n57 = 8'hc5 >> { _00_, \period[3] , _04_ };
  assign _04_ = 16'h01fe >> { \cntr[3] , \cntr[0] , \cntr[2] , \cntr[1]  };
  assign n62 = 16'haa3c >> { _00_, _02_, \cntr[4] , \period[4]  };
  assign n67 = 8'h0b >> { _05_, _00_, \period[5]  };
  assign _05_ = 8'h4b >> { \cntr[5] , _02_, \cntr[4]  };
  assign n72 = 16'h0ef0 >> { _06_, \cntr[6] , \cntr[7] , \period[6]  };
  assign _06_ = 8'h10 >> { _02_, \cntr[4] , \cntr[5]  };
  assign n77 = 8'h2c >> { _01_, \cntr[7] , \period[7]  };
  assign _07_ = 16'h9000 >> { _08_, _09_, \cntr[5] , \duty[5]  };
  assign _08_ = 16'hb0bb >> { \cntr[6] , \duty[6] , \duty[1] , \cntr[1]  };
  assign _09_ = 16'hb00b >> { \cntr[0] , \duty[0] , \cntr[1] , \duty[1]  };
  assign _10_ = 16'hb00b >> { \cntr[4] , \duty[4] , \duty[6] , \cntr[6]  };
  assign _11_ = 16'h9009 >> { \cntr[2] , \duty[2] , \cntr[3] , \duty[3]  };
  assign _12_ = 16'h9000 >> { _11_, _10_, \cntr[7] , \duty[7]  };
  assign n38 = 16'hf444 >> { _12_, _07_, pwm, _00_ };
endmodule
