/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module seconds_decoder(clk, \decoder_out[0] , \decoder_out[1] , \decoder_out[2] , \decoder_out[3] , \decoder_out[4] , \decoder_out[5] , \decoder_out[6] , \decoder_out[7] );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input clk;
  wire clk;
  reg \count[0] ;
  reg \count[10] ;
  reg \count[11] ;
  reg \count[12] ;
  reg \count[13] ;
  reg \count[14] ;
  reg \count[15] ;
  reg \count[16] ;
  reg \count[17] ;
  reg \count[18] ;
  reg \count[19] ;
  reg \count[1] ;
  reg \count[20] ;
  reg \count[21] ;
  reg \count[22] ;
  reg \count[23] ;
  reg \count[2] ;
  reg \count[3] ;
  reg \count[4] ;
  reg \count[5] ;
  reg \count[6] ;
  reg \count[7] ;
  reg \count[8] ;
  reg \count[9] ;
  reg \decoder_in[0] ;
  reg \decoder_in[1] ;
  reg \decoder_in[2] ;
  output \decoder_out[0] ;
  reg \decoder_out[0] ;
  output \decoder_out[1] ;
  reg \decoder_out[1] ;
  output \decoder_out[2] ;
  reg \decoder_out[2] ;
  output \decoder_out[3] ;
  reg \decoder_out[3] ;
  output \decoder_out[4] ;
  reg \decoder_out[4] ;
  output \decoder_out[5] ;
  reg \decoder_out[5] ;
  output \decoder_out[6] ;
  reg \decoder_out[6] ;
  output \decoder_out[7] ;
  reg \decoder_out[7] ;
  wire n102;
  wire n107;
  wire n112;
  wire n117;
  wire n122;
  wire n127;
  wire n132;
  wire n137;
  wire n142;
  wire n147;
  wire n152;
  wire n157;
  wire n162;
  wire n167;
  wire n172;
  wire n177;
  wire n182;
  wire n20;
  wire n24;
  wire n28;
  wire n32;
  wire n36;
  wire n40;
  wire n44;
  wire n48;
  wire n52;
  wire n57;
  wire n62;
  wire n67;
  wire n72;
  wire n77;
  wire n82;
  wire n87;
  wire n92;
  wire n97;
  always @(posedge clk)
    \decoder_out[0]  <= n20;
  always @(posedge clk)
    \decoder_in[1]  <= n57;
  always @(posedge clk)
    \decoder_in[2]  <= n62;
  always @(posedge clk)
    \count[0]  <= n67;
  always @(posedge clk)
    \count[1]  <= n72;
  always @(posedge clk)
    \count[2]  <= n77;
  always @(posedge clk)
    \count[3]  <= n82;
  always @(posedge clk)
    \count[4]  <= n87;
  always @(posedge clk)
    \count[5]  <= n92;
  always @(posedge clk)
    \count[6]  <= n97;
  always @(posedge clk)
    \count[7]  <= n102;
  always @(posedge clk)
    \decoder_out[1]  <= n24;
  always @(posedge clk)
    \count[8]  <= n107;
  always @(posedge clk)
    \count[9]  <= n112;
  always @(posedge clk)
    \count[10]  <= n117;
  always @(posedge clk)
    \count[11]  <= n122;
  always @(posedge clk)
    \count[12]  <= n127;
  always @(posedge clk)
    \count[13]  <= n132;
  always @(posedge clk)
    \count[14]  <= n137;
  always @(posedge clk)
    \count[15]  <= n142;
  always @(posedge clk)
    \count[16]  <= n147;
  always @(posedge clk)
    \count[17]  <= n152;
  always @(posedge clk)
    \decoder_out[2]  <= n28;
  always @(posedge clk)
    \count[18]  <= n157;
  always @(posedge clk)
    \count[19]  <= n162;
  always @(posedge clk)
    \count[20]  <= n167;
  always @(posedge clk)
    \count[21]  <= n172;
  always @(posedge clk)
    \count[22]  <= n177;
  always @(posedge clk)
    \count[23]  <= n182;
  always @(posedge clk)
    \decoder_out[3]  <= n32;
  always @(posedge clk)
    \decoder_out[4]  <= n36;
  always @(posedge clk)
    \decoder_out[5]  <= n40;
  always @(posedge clk)
    \decoder_out[6]  <= n44;
  always @(posedge clk)
    \decoder_out[7]  <= n48;
  always @(posedge clk)
    \decoder_in[0]  <= n52;
  assign n62 = 16'h7f80 >> { \decoder_in[2] , _03_, \decoder_in[0] , \decoder_in[1]  };
  assign _03_ = 4'h8 >> { _04_, _09_ };
  assign _04_ = 16'h0100 >> { _05_, \count[13] , \count[14] , \count[15]  };
  assign _05_ = 16'h0100 >> { _06_, \count[10] , \count[11] , \count[12]  };
  assign _06_ = 16'h0100 >> { _07_, \count[7] , \count[8] , \count[9]  };
  assign _07_ = 16'h0100 >> { _08_, \count[6] , \count[4] , \count[5]  };
  assign _08_ = 16'h0001 >> { \count[0] , \count[2] , \count[3] , \count[1]  };
  assign _09_ = 16'h1000 >> { _10_, _12_, \count[16] , \count[23]  };
  assign _10_ = 8'h10 >> { _11_, \count[21] , \count[22]  };
  assign _11_ = 4'h1 >> { \count[19] , \count[20]  };
  assign _12_ = 4'h1 >> { \count[17] , \count[18]  };
  assign n20 = 16'h8001 >> { _03_, \decoder_in[0] , \decoder_in[1] , \decoder_in[2]  };
  assign n24 = 16'h0110 >> { _03_, \decoder_in[0] , \decoder_in[1] , \decoder_in[2]  };
  assign n28 = 16'h1004 >> { _03_, \decoder_in[0] , \decoder_in[1] , \decoder_in[2]  };
  assign n32 = 16'h1400 >> { \decoder_in[1] , _03_, \decoder_in[0] , \decoder_in[2]  };
  assign n36 = 16'h4002 >> { _03_, \decoder_in[0] , \decoder_in[1] , \decoder_in[2]  };
  assign n40 = 16'h1400 >> { \decoder_in[2] , _03_, \decoder_in[0] , \decoder_in[1]  };
  assign n44 = 16'h4200 >> { \decoder_in[2] , _03_, \decoder_in[0] , \decoder_in[1]  };
  assign n48 = 16'h6000 >> { \decoder_in[1] , \decoder_in[2] , _03_, \decoder_in[0]  };
  assign n57 = 8'h78 >> { \decoder_in[1] , _03_, \decoder_in[0]  };
  assign n52 = 4'h6 >> { _03_, \decoder_in[0]  };
  assign n72 = 4'h9 >> { \count[0] , \count[1]  };
  assign n77 = 8'he1 >> { \count[2] , \count[0] , \count[1]  };
  assign n82 = 16'hfe01 >> { \count[3] , \count[0] , \count[2] , \count[1]  };
  assign n87 = 4'h6 >> { _08_, \count[4]  };
  assign n92 = 8'hb4 >> { \count[5] , _08_, \count[4]  };
  assign n97 = 4'h1 >> { _03_, _13_ };
  assign _13_ = 16'h10ef >> { \count[6] , _08_, \count[4] , \count[5]  };
  assign n102 = 8'h14 >> { _07_, \count[7] , _03_ };
  assign n107 = 8'hb4 >> { \count[8] , _07_, \count[7]  };
  assign n112 = 16'hef10 >> { \count[9] , _07_, \count[7] , \count[8]  };
  assign n117 = 8'h14 >> { _06_, \count[10] , _03_ };
  assign n122 = 8'hb4 >> { \count[11] , _06_, \count[10]  };
  assign n127 = 4'h1 >> { _03_, _14_ };
  assign _14_ = 16'h10ef >> { \count[12] , _06_, \count[10] , \count[11]  };
  assign n132 = 8'h14 >> { _05_, \count[13] , _03_ };
  assign n137 = 8'hb4 >> { \count[14] , _05_, \count[13]  };
  assign n142 = 8'h1c >> { _00_, \count[15] , _09_ };
  assign _00_ = 8'h10 >> { _05_, \count[13] , \count[14]  };
  assign n147 = 8'h14 >> { _04_, \count[16] , _09_ };
  assign n152 = 16'h4f10 >> { \count[17] , _04_, \count[16] , _09_ };
  assign n157 = 16'hef10 >> { \count[18] , _04_, \count[16] , \count[17]  };
  assign n162 = 4'h6 >> { _01_, \count[19]  };
  assign _01_ = 8'h40 >> { _04_, _12_, \count[16]  };
  assign n167 = 16'h0b04 >> { \count[20] , _03_, _01_, \count[19]  };
  assign n172 = 8'h14 >> { _02_, \count[21] , _03_ };
  assign _02_ = 16'h4000 >> { _04_, _11_, _12_, \count[16]  };
  assign n177 = 8'hb4 >> { \count[22] , _02_, \count[21]  };
  assign n182 = 8'h70 >> { \count[23] , _01_, _10_ };
  assign n67 = 2'h1 >> \count[0] ;
endmodule
