/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module shift_reg(clock, reset, \control[0] , \control[1] , in, \out[0] , \out[1] , \out[2] , \out[3] , \out[4] , \out[5] , \out[6] , \out[7] );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input clock;
  wire clock;
  input \control[0] ;
  wire \control[0] ;
  input \control[1] ;
  wire \control[1] ;
  input in;
  wire in;
  wire n28;
  wire n32;
  wire n36;
  wire n40;
  wire n44;
  wire n48;
  wire n52;
  wire n56;
  output \out[0] ;
  reg \out[0] ;
  output \out[1] ;
  reg \out[1] ;
  output \out[2] ;
  reg \out[2] ;
  output \out[3] ;
  reg \out[3] ;
  output \out[4] ;
  reg \out[4] ;
  output \out[5] ;
  reg \out[5] ;
  output \out[6] ;
  reg \out[6] ;
  output \out[7] ;
  reg \out[7] ;
  input reset;
  wire reset;
  always @(posedge clock)
    \out[0]  <= n28;
  always @(posedge clock)
    \out[1]  <= n32;
  always @(posedge clock)
    \out[2]  <= n36;
  always @(posedge clock)
    \out[3]  <= n40;
  always @(posedge clock)
    \out[4]  <= n44;
  always @(posedge clock)
    \out[5]  <= n48;
  always @(posedge clock)
    \out[6]  <= n52;
  always @(posedge clock)
    \out[7]  <= n56;
  assign _00_ = 8'hca >> { \control[1] , in, \out[0]  };
  assign n32 = 16'h0c0a >> { \control[0] , reset, \out[2] , _01_ };
  assign _01_ = 8'hca >> { \control[1] , \out[0] , \out[1]  };
  assign n36 = 16'h0c0a >> { \control[0] , reset, \out[3] , _02_ };
  assign _02_ = 8'hca >> { \control[1] , \out[1] , \out[2]  };
  assign n40 = 16'h0c0a >> { \control[0] , reset, \out[4] , _03_ };
  assign _03_ = 8'hca >> { \control[1] , \out[2] , \out[3]  };
  assign n44 = 16'h0c0a >> { \control[0] , reset, \out[5] , _04_ };
  assign _04_ = 8'hca >> { \control[1] , \out[3] , \out[4]  };
  assign n48 = 16'h0c0a >> { \control[0] , reset, \out[6] , _05_ };
  assign _05_ = 8'hca >> { \control[1] , \out[4] , \out[5]  };
  assign n52 = 16'h0c0a >> { \control[0] , reset, \out[7] , _06_ };
  assign _06_ = 8'hca >> { \control[1] , \out[5] , \out[6]  };
  assign n56 = 16'h0c0a >> { \control[0] , reset, in, _07_ };
  assign _07_ = 8'hca >> { \control[1] , \out[6] , \out[7]  };
  assign n28 = 16'h0c0a >> { \control[0] , reset, \out[1] , _00_ };
endmodule
