/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module fpga_LFSR(clk, \out[0] , \out[1] , \out[2] , \out[3] , \out[4] , \out[5] , \out[6] , \out[7] , \out[8] , \out[9] , \out[10] , \out[11] , \out[12] , \out[13] , \out[14] , \out[15] , \out[16] , \out[17] , \out[18] , \out[19] 
, \out[20] , \out[21] , \out[22] , \out[23] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  input clk;
  wire clk;
  reg \cntr[0]  = 1'h0;
  reg \cntr[10]  = 1'h0;
  reg \cntr[11]  = 1'h0;
  reg \cntr[12]  = 1'h0;
  reg \cntr[13]  = 1'h0;
  reg \cntr[14]  = 1'h0;
  reg \cntr[15]  = 1'h0;
  reg \cntr[16]  = 1'h0;
  reg \cntr[17]  = 1'h0;
  reg \cntr[18]  = 1'h0;
  reg \cntr[19]  = 1'h0;
  reg \cntr[1]  = 1'h0;
  reg \cntr[20]  = 1'h0;
  reg \cntr[21]  = 1'h0;
  reg \cntr[22]  = 1'h0;
  reg \cntr[23]  = 1'h0;
  reg \cntr[2]  = 1'h0;
  reg \cntr[3]  = 1'h0;
  reg \cntr[4]  = 1'h0;
  reg \cntr[5]  = 1'h0;
  reg \cntr[6]  = 1'h0;
  reg \cntr[7]  = 1'h0;
  reg \cntr[8]  = 1'h0;
  reg \cntr[9]  = 1'h0;
  wire n102;
  wire n107;
  wire n112;
  wire n117;
  wire n122;
  wire n127;
  wire n132;
  wire n137;
  wire n142;
  wire n147;
  wire n152;
  wire n157;
  wire n162;
  wire n167;
  wire n172;
  wire n176;
  wire n180;
  wire n184;
  wire n188;
  wire n192;
  wire n196;
  wire n200;
  wire n204;
  wire n208;
  wire n212;
  wire n216;
  wire n220;
  wire n224;
  wire n228;
  wire n232;
  wire n236;
  wire n240;
  wire n244;
  wire n248;
  wire n252;
  wire n256;
  wire n260;
  wire n264;
  wire n52;
  wire n57;
  wire n62;
  wire n67;
  wire n72;
  wire n77;
  wire n82;
  wire n87;
  wire n92;
  wire n97;
  output \out[0] ;
  reg \out[0]  = 1'h0;
  output \out[10] ;
  reg \out[10]  = 1'h0;
  output \out[11] ;
  reg \out[11]  = 1'h0;
  output \out[12] ;
  reg \out[12]  = 1'h0;
  output \out[13] ;
  reg \out[13]  = 1'h0;
  output \out[14] ;
  reg \out[14]  = 1'h0;
  output \out[15] ;
  reg \out[15]  = 1'h0;
  output \out[16] ;
  reg \out[16]  = 1'h0;
  output \out[17] ;
  reg \out[17]  = 1'h0;
  output \out[18] ;
  reg \out[18]  = 1'h0;
  output \out[19] ;
  reg \out[19]  = 1'h0;
  output \out[1] ;
  reg \out[1]  = 1'h0;
  output \out[20] ;
  reg \out[20]  = 1'h0;
  output \out[21] ;
  reg \out[21]  = 1'h0;
  output \out[22] ;
  reg \out[22]  = 1'h0;
  output \out[23] ;
  reg \out[23]  = 1'h0;
  output \out[2] ;
  reg \out[2]  = 1'h0;
  output \out[3] ;
  reg \out[3]  = 1'h0;
  output \out[4] ;
  reg \out[4]  = 1'h0;
  output \out[5] ;
  reg \out[5]  = 1'h0;
  output \out[6] ;
  reg \out[6]  = 1'h0;
  output \out[7] ;
  reg \out[7]  = 1'h0;
  output \out[8] ;
  reg \out[8]  = 1'h0;
  output \out[9] ;
  reg \out[9]  = 1'h0;
  always @(posedge clk)
    \cntr[0]  <= n52;
  always @(posedge clk)
    \cntr[9]  <= n97;
  always @(posedge clk)
    \cntr[10]  <= n102;
  always @(posedge clk)
    \cntr[11]  <= n107;
  always @(posedge clk)
    \cntr[12]  <= n112;
  always @(posedge clk)
    \cntr[13]  <= n117;
  always @(posedge clk)
    \cntr[14]  <= n122;
  always @(posedge clk)
    \cntr[15]  <= n127;
  always @(posedge clk)
    \cntr[16]  <= n132;
  always @(posedge clk)
    \cntr[17]  <= n137;
  always @(posedge clk)
    \cntr[18]  <= n142;
  always @(posedge clk)
    \cntr[1]  <= n57;
  always @(posedge clk)
    \cntr[19]  <= n147;
  always @(posedge clk)
    \cntr[20]  <= n152;
  always @(posedge clk)
    \cntr[21]  <= n157;
  always @(posedge clk)
    \cntr[22]  <= n162;
  always @(posedge clk)
    \cntr[23]  <= n167;
  always @(posedge clk)
    \out[0]  <= n172;
  always @(posedge clk)
    \out[1]  <= n176;
  always @(posedge clk)
    \out[2]  <= n180;
  always @(posedge clk)
    \out[3]  <= n184;
  always @(posedge clk)
    \out[4]  <= n188;
  always @(posedge clk)
    \cntr[2]  <= n62;
  always @(posedge clk)
    \out[5]  <= n192;
  always @(posedge clk)
    \out[6]  <= n196;
  always @(posedge clk)
    \out[7]  <= n200;
  always @(posedge clk)
    \out[8]  <= n204;
  always @(posedge clk)
    \out[9]  <= n208;
  always @(posedge clk)
    \out[10]  <= n212;
  always @(posedge clk)
    \out[11]  <= n216;
  always @(posedge clk)
    \out[12]  <= n220;
  always @(posedge clk)
    \out[13]  <= n224;
  always @(posedge clk)
    \out[14]  <= n228;
  always @(posedge clk)
    \cntr[3]  <= n67;
  always @(posedge clk)
    \out[15]  <= n232;
  always @(posedge clk)
    \out[16]  <= n236;
  always @(posedge clk)
    \out[17]  <= n240;
  always @(posedge clk)
    \out[18]  <= n244;
  always @(posedge clk)
    \out[19]  <= n248;
  always @(posedge clk)
    \out[20]  <= n252;
  always @(posedge clk)
    \out[21]  <= n256;
  always @(posedge clk)
    \out[22]  <= n260;
  always @(posedge clk)
    \out[23]  <= n264;
  always @(posedge clk)
    \cntr[4]  <= n72;
  always @(posedge clk)
    \cntr[5]  <= n77;
  always @(posedge clk)
    \cntr[6]  <= n82;
  always @(posedge clk)
    \cntr[7]  <= n87;
  always @(posedge clk)
    \cntr[8]  <= n92;
  assign n236 = 8'hca >> { _001_, \out[15] , \out[16]  };
  assign n240 = 8'hca >> { _001_, \out[16] , \out[17]  };
  assign n244 = 8'hca >> { _001_, \out[17] , \out[18]  };
  assign n248 = 8'hca >> { _001_, \out[18] , \out[19]  };
  assign n252 = 8'hca >> { _001_, \out[19] , \out[20]  };
  assign n256 = 8'hca >> { _001_, \out[20] , \out[21]  };
  assign n260 = 8'hca >> { _001_, \out[21] , \out[22]  };
  assign n264 = 8'hca >> { _001_, \out[22] , \out[23]  };
  assign n52 = 2'h1 >> \cntr[0] ;
  assign n57 = 4'h9 >> { \cntr[0] , \cntr[1]  };
  assign n62 = 8'he1 >> { \cntr[2] , \cntr[0] , \cntr[1]  };
  assign n67 = 16'hfe01 >> { \cntr[3] , \cntr[0] , \cntr[2] , \cntr[1]  };
  assign n72 = 4'h6 >> { _000_, \cntr[4]  };
  assign _000_ = 16'h0001 >> { \cntr[0] , \cntr[2] , \cntr[3] , \cntr[1]  };
  assign n77 = 8'hb4 >> { \cntr[5] , _000_, \cntr[4]  };
  assign n82 = 16'hef10 >> { \cntr[6] , _000_, \cntr[4] , \cntr[5]  };
  assign n87 = 8'h14 >> { _006_, \cntr[7] , _001_ };
  assign _001_ = 8'h40 >> { _002_, _007_, \cntr[20]  };
  assign _002_ = 16'h0100 >> { _003_, \cntr[16] , \cntr[17] , \cntr[18]  };
  assign _003_ = 16'h0100 >> { _004_, \cntr[13] , \cntr[14] , \cntr[15]  };
  assign _004_ = 16'h0100 >> { _005_, \cntr[10] , \cntr[11] , \cntr[12]  };
  assign _005_ = 16'h0100 >> { _006_, \cntr[7] , \cntr[8] , \cntr[9]  };
  assign _006_ = 16'h0100 >> { _000_, \cntr[6] , \cntr[4] , \cntr[5]  };
  assign _007_ = 16'h0001 >> { \cntr[19] , \cntr[21] , \cntr[22] , \cntr[23]  };
  assign n92 = 16'h0b04 >> { \cntr[8] , _001_, _006_, \cntr[7]  };
  assign n97 = 16'hef10 >> { \cntr[9] , _006_, \cntr[7] , \cntr[8]  };
  assign n102 = 4'h6 >> { _005_, \cntr[10]  };
  assign n107 = 16'h0b04 >> { \cntr[11] , _001_, _005_, \cntr[10]  };
  assign n112 = 16'hef10 >> { \cntr[12] , _005_, \cntr[10] , \cntr[11]  };
  assign n117 = 8'h14 >> { _004_, \cntr[13] , _001_ };
  assign n122 = 16'h0b04 >> { \cntr[14] , _001_, _004_, \cntr[13]  };
  assign n127 = 16'hef10 >> { \cntr[15] , _004_, \cntr[13] , \cntr[14]  };
  assign n132 = 8'h14 >> { _003_, \cntr[16] , _001_ };
  assign n137 = 16'h0b04 >> { \cntr[17] , _001_, _003_, \cntr[16]  };
  assign n142 = 4'h1 >> { _001_, _008_ };
  assign _008_ = 16'h10ef >> { \cntr[18] , _003_, \cntr[16] , \cntr[17]  };
  assign n147 = 4'h6 >> { _002_, \cntr[19]  };
  assign n152 = 8'hb4 >> { \cntr[20] , _002_, \cntr[19]  };
  assign n157 = 4'h1 >> { _001_, _009_ };
  assign _009_ = 16'h10ef >> { \cntr[21] , _002_, \cntr[19] , \cntr[20]  };
  assign n162 = 8'h14 >> { _010_, \cntr[22] , _001_ };
  assign _010_ = 16'h0100 >> { _002_, \cntr[19] , \cntr[20] , \cntr[21]  };
  assign n167 = 8'hb4 >> { \cntr[23] , _010_, \cntr[22]  };
  assign n172 = 8'hca >> { _001_, _011_, \out[0]  };
  assign _011_ = 16'h9669 >> { \out[16] , \out[21] , \out[22] , \out[23]  };
  assign n176 = 8'hca >> { _001_, \out[0] , \out[1]  };
  assign n180 = 8'hca >> { _001_, \out[1] , \out[2]  };
  assign n184 = 8'hca >> { _001_, \out[2] , \out[3]  };
  assign n188 = 8'hca >> { _001_, \out[3] , \out[4]  };
  assign n192 = 8'hca >> { _001_, \out[4] , \out[5]  };
  assign n196 = 8'hca >> { _001_, \out[5] , \out[6]  };
  assign n200 = 8'hca >> { _001_, \out[6] , \out[7]  };
  assign n204 = 8'hca >> { _001_, \out[7] , \out[8]  };
  assign n208 = 8'hca >> { _001_, \out[8] , \out[9]  };
  assign n212 = 8'hca >> { _001_, \out[9] , \out[10]  };
  assign n216 = 8'hca >> { _001_, \out[10] , \out[11]  };
  assign n220 = 8'hca >> { _001_, \out[11] , \out[12]  };
  assign n224 = 8'hca >> { _001_, \out[12] , \out[13]  };
  assign n228 = 8'hca >> { _001_, \out[13] , \out[14]  };
  assign n232 = 8'hca >> { _001_, \out[14] , \out[15]  };
endmodule
