/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module and2_latch(a, b, clk, rst, c, d);
  input a;
  wire a;
  input b;
  wire b;
  output c;
  wire c;
  input clk;
  wire clk;
  output d;
  reg d;
  wire n14;
  input rst;
  wire rst;
  always @(posedge clk)
    d <= n14;
  assign c = 4'h8 >> { a, b };
  assign n14 = 8'h40 >> { b, a, rst };
endmodule
