/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module decoder_3_to_8(in_0_ , in_1_ , in_2_ , en, out_0_ , out_1_ , out_2_ , out_3_ , out_4_ , out_5_ , out_6_ , out_7_ );
  input en;
  wire en;
  input in_0_ ;
  wire in_0_ ;
  input in_1_ ;
  wire in_1_ ;
  input in_2_ ;
  wire in_2_ ;
  output out_0_ ;
  wire out_0_ ;
  output out_1_ ;
  wire out_1_ ;
  output out_2_ ;
  wire out_2_ ;
  output out_3_ ;
  wire out_3_ ;
  output out_4_ ;
  wire out_4_ ;
  output out_5_ ;
  wire out_5_ ;
  output out_6_ ;
  wire out_6_ ;
  output out_7_ ;
  wire out_7_ ;
  assign out_0_  = 16'h0100 >> { en, in_2_ , in_1_ , in_0_  };
  assign out_1_  = 16'h1000 >> { in_0_ , en, in_2_ , in_1_  };
  assign out_2_  = 16'h1000 >> { in_1_ , en, in_2_ , in_0_  };
  assign out_3_  = 16'h4000 >> { en, in_1_ , in_0_ , in_2_  };
  assign out_4_  = 16'h1000 >> { in_2_ , en, in_1_ , in_0_  };
  assign out_5_  = 16'h4000 >> { en, in_2_ , in_0_ , in_1_  };
  assign out_6_  = 16'h4000 >> { en, in_1_ , in_2_ , in_0_  };
  assign out_7_  = 16'h8000 >> { in_2_ , in_1_ , in_0_ , en };
endmodule
